routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\Frontend\SiteController::class, 'index'])->name('root');
Route::get('/allpost', [App\Http\Controllers\Frontend\SiteController::class, 'allpost'])->name('allpost');
Route::get('/course', [App\Http\Controllers\Frontend\SiteController::class, 'course'])->name('course');
Route::get('/about', [App\Http\Controllers\Frontend\SiteController::class, 'about'])->name('about');
Route::get('/about/facility', [App\Http\Controllers\Frontend\SiteController::class, 'facility'])->name('facility');
Route::get('/partner', [App\Http\Controllers\Frontend\SiteController::class, 'partner'])->name('partner');
Route::get('/about/governance', [App\Http\Controllers\Frontend\SiteController::class, 'governance'])->name('governance');
Route::get('/about/symbol', [App\Http\Controllers\Frontend\SiteController::class, 'symbol'])->name('symbol');
Route::get('/academic/accreditation', [App\Http\Controllers\Frontend\SiteController::class, 'accreditation'])->name('accreditation');
Route::get('/student/download', [App\Http\Controllers\Frontend\SiteController::class, 'download'])->name('download');
Route::get('/student/hima', [App\Http\Controllers\Frontend\SiteController::class, 'hima'])->name('hima');
Route::get('/academic/research', [App\Http\Controllers\Frontend\SiteController::class, 'research'])->name('research');
Route::get('/academic/personil', [App\Http\Controllers\Frontend\SiteController::class, 'personil'])->name('personil');
Route::resource('comments', '\App\Http\Controllers\Backend\PostCommentController');

Route::get('/post/{slug}', [App\Http\Controllers\Frontend\SiteController::class, 'singlepost'])->name('singlepost');
Auth::routes([
    'register' => false,
    'verify' => true
]);

Route::middleware('has.role')->group(function () {
    Route::prefix('role-and-permission')->namespace('Permissions')->group(function () {
        Route::prefix('roles')->group(function () {
            Route::get('', [App\Http\Controllers\Permissions\RoleController::class, 'index'])->name('roles.index');
            Route::post('create', [App\Http\Controllers\Permissions\RoleController::class, 'store'])->name('roles.create');
            Route::get('{role}/edit', [App\Http\Controllers\Permissions\RoleController::class, 'edit'])->name('roles.edit');
            Route::put('{role}/edit', [App\Http\Controllers\Permissions\RoleController::class, 'update']);
            Route::get('{role}/delete', [App\Http\Controllers\Permissions\RoleController::class, 'delete'])->name('roles.delete');
        });
        Route::prefix('permissions')->group(function () {
            Route::get('', [App\Http\Controllers\Permissions\PermissionController::class, 'index'])->name('permissions.index');
            Route::post('create', [App\Http\Controllers\Permissions\PermissionController::class, 'store'])->name('permissions.create');
            Route::get('{permission}/edit', [App\Http\Controllers\Permissions\PermissionController::class, 'edit'])->name('permissions.edit');
            Route::put('{permission}/edit', [App\Http\Controllers\Permissions\PermissionController::class, 'update']);
            Route::get('{permission}/delete', [App\Http\Controllers\Permissions\PermissionController::class, 'delete'])->name('permissions.delete');
        });
        Route::get('assignable', [App\Http\Controllers\Permissions\AssignController::class, 'create'])->name('assign.create');
        Route::post('assignable', [App\Http\Controllers\Permissions\AssignController::class, 'store'])->name('assign.store');
        Route::get('assignable/{role}/edit', [App\Http\Controllers\Permissions\AssignController::class, 'edit'])->name('assign.edit');
        Route::put('assignable/{role}/update', [App\Http\Controllers\Permissions\AssignController::class, 'update'])->name('assign.update');
    });
    Route::prefix('admin')->group(function () {
        Route::group(['middleware' => ['permission:show posts']], function () {
            Route::resource('posts', '\App\Http\Controllers\Backend\PostController');
            Route::get('data/posts', '\App\Http\Controllers\Backend\DataTable\PostController')->name('data.posts');
        });
        Route::group(['middleware' => ['permission:show categories']], function () {
            Route::resource('categories', '\App\Http\Controllers\Backend\CategoryController');
            Route::get('data/categories', '\App\Http\Controllers\Backend\DataTable\CategoryController')->name('data.categories');
        });

        Route::group(['middleware' => ['permission:show courses']], function () {
            Route::resource('courses', '\App\Http\Controllers\Backend\CourseController');
            Route::get('data/courses', '\App\Http\Controllers\Backend\DataTable\CourseController')->name('data.courses');
        });

        Route::group(['middleware' => ['permission:show visions']], function () {
            Route::resource('visions', '\App\Http\Controllers\Backend\VisionController');
            Route::get('data/visions', '\App\Http\Controllers\Backend\DataTable\VisionController')->name('data.visions');
        });

        Route::group(['middleware' => ['permission:show sliders']], function () {
            Route::resource('sliders', '\App\Http\Controllers\Backend\SliderController');
            Route::get('data/sliders', '\App\Http\Controllers\Backend\DataTable\SliderController')->name('data.sliders');
        });
        Route::group(['middleware' => ['permission:show governances']], function () {
            Route::resource('governances', '\App\Http\Controllers\Backend\GovernanceController');
            Route::get('data/governances', '\App\Http\Controllers\Backend\DataTable\GovernanceController')->name('data.governances');
        });
        Route::group(['middleware' => ['permission:show symbols']], function () {
            Route::resource('symbols', '\App\Http\Controllers\Backend\SymbolController');
            Route::get('data/symbols', '\App\Http\Controllers\Backend\DataTable\SymbolController')->name('data.symbols');
        });
        Route::group(['middleware' => ['permission:show lecturers']], function () {
            Route::resource('lecturers', '\App\Http\Controllers\Backend\LecturerController');
            Route::get('data/lecturers', '\App\Http\Controllers\Backend\DataTable\LecturerController')->name('data.lecturers');
        });
        Route::group(['middleware' => ['permission:show partners']], function () {
            Route::resource('partners', '\App\Http\Controllers\Backend\PartnerController');
            Route::get('data/partners', '\App\Http\Controllers\Backend\DataTable\PartnerController')->name('data.partners');
        });
        Route::group(['middleware' => ['permission:show documents']], function () {
            Route::resource('documents', '\App\Http\Controllers\Backend\DocumentController');
            Route::get('data/documents', '\App\Http\Controllers\Backend\DataTable\DocumentController')->name('data.documents');
        });
        Route::group(['middleware' => ['permission:show facilities']], function () {
            Route::resource('facilities', '\App\Http\Controllers\Backend\FacilityController');
            Route::get('data/facilities', '\App\Http\Controllers\Backend\DataTable\FacilityController')->name('data.facilities');
        });
        Route::group(['middleware' => ['permission:show users']], function () {
            Route::resource('users', '\App\Http\Controllers\Backend\UserController');
            Route::get('data/users', '\App\Http\Controllers\Backend\DataTable\UserController')->name('data.users');
        });
        Route::group(['middleware' => ['permission:show himas']], function () {
            Route::resource('himas', '\App\Http\Controllers\Backend\HimaController');
            Route::get('data/himas', '\App\Http\Controllers\Backend\DataTable\HimaController')->name('data.himas');
        });
        Route::group(['middleware' => ['permission:show comments']], function () {
            Route::resource('comments', '\App\Http\Controllers\Backend\PostCommentController');
            Route::get('data/comments', '\App\Http\Controllers\Backend\DataTable\PostCommentController')->name('data.comments');
        });
    });
});
Route::get('/home', [App\Http\Controllers\HomeController::class, 'dashboard'])->name('home')->middleware('verified');

app/Models/Vision.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Vision extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function getImage()
    {
        return asset('storage/' . $this->image);
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.category.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        request()->validate([
            'name' => 'required|min:3|unique:categories,name'
        ]);

        Category::create([
            'name' => request('name'),
            'slug' => Str::slug(request('name')),
        ]);

        session()->flash('message', 'Successfully Added');

        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('backend.category.edit', [
            'category' => $category
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Category $category)
    {
        request()->validate([
            'name' => 'required|min:3'
        ]);

        $category->update([
            'name' => request('name'),
            'slug' => Str::slug(request('name')),
        ]);

        session()->flash('message', 'Successfully Updated');

        return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        session()->flash('message', 'Successfully Deleted');
        return view('backend.category.index');
    }
}

app/Http/Controllers/Backend/CourseController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Course;
use Illuminate\Http\Request;

class CourseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.course.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.course.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        request()->validate([
            'code' => 'required',
            'name' => 'required',
            'credit' => 'required|numeric',
            'semester' => 'required|numeric',
            'description' => 'required'
        ]);

        Course::create([
            'code' => request('code'),
            'name' => request('name'),
            'credit' => request('credit'),
            'semester' => request('semester'),
            'description' => request('description')
        ]);

        session()->flash('message', 'Successfully Added');

        return redirect()->route('courses.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Course $course)
    {
        return view('backend.course.edit', compact('course'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Course $course)
    {
        request()->validate([
            'code' => 'required',
            'name' => 'required',
            'credit' => 'required|numeric',
            'semester' => 'required|numeric'
        ]);

        $course->update([
            'code' => request('code'),
            'name' => request('name'),
            'credit' => request('credit'),
            'semester' => request('semester'),
            'description' => request('description')
        ]);

        session()->flash('message', 'Successfully Updated');

        return redirect()->route('courses.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Course $course)
    {
        $course->delete();
        session()->flash('message', 'Successfully Deleted');
        return view('backend.course.index');
    }
}

app/Http/Controllers/Backend/DataTable/CategoryController.php
<?php

namespace App\Http\Controllers\Backend\DataTable;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke()
    {
        $categories = Category::orderBy('name', 'asc');

        return datatables()->of($categories)
            ->addColumn('action', 'backend.datatable-action.datatable-action')
            ->addIndexColumn()
            ->toJson();
    }
}

app/Http/Controllers/Backend/DataTable/CourseController.php
<?php

namespace App\Http\Controllers\Backend\DataTable;

use App\Http\Controllers\Controller;
use App\Models\Course;
use Illuminate\Http\Request;

class CourseController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        $courses = Course::orderBy('semester', 'asc');

        return datatables()->of($courses)
            ->addColumn('action', 'backend.datatable-action.datatable-action')
            ->addIndexColumn()
            ->toJson();
    }
}

app/Http/Controllers/Backend/DataTable/DocumentController.php
<?php

namespace App\Http\Controllers\Backend\DataTable;

use App\Http\Controllers\Controller;
use App\Models\Document;
use Illuminate\Http\Request;

class DocumentController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        $documents = Document::orderBy('created_at', 'desc');

        return datatables()->of($documents)
            ->addColumn('action', 'backend.datatable-action.datatable-action')
            ->addIndexColumn()
            ->addColumn('created', function (Document $document) {
                return $document->created_at->format('d M Y');
            })
            ->toJson();
    }
}

app/Http/Controllers/Backend/DataTable/FacilityController.php
<?php

namespace App\Http\Controllers\Backend\DataTable;

use App\Http\Controllers\Controller;
use App\Models\Facility;
use Illuminate\Http\Request;

class FacilityController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        $facilities = Facility::orderBy('created_at', 'asc');

        return datatables()->of($facilities)
            ->addColumn('action', 'backend.datatable-action.datatable-action')
            ->addColumn('image', function (Facility $facility) {
                return '<img src="' . $facility->getImage() . '" height="120px"/>';
            })
            ->addIndexColumn()
            ->rawColumns(['image', 'action'])
            ->toJson();
    }
}

resources/views/backend/vision/create.blade.php
@extends('backend.master')
@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="card card-info">
            <div class="card-header">
                <h3 class="card-title">Create Our Vision</h3>
            </div>

            <form action="{{ route('visions.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="welcome">Welcome Speech Head Of TRPL</label>
                        <textarea name="welcome" id="welcome" class="form-control summernote @error('welcome') is-invalid  @enderror"> {{ old('welcome') }} </textarea>
                        @error('welcome')
                            <span class="invalid-feedback">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="vision">Our Vision</label>
                        <textarea name="vision" id="vision" class="form-control summernote @error('vision') is-invalid  @enderror"> {{ old('vision') }} </textarea>
                        @error('vision')
                            <span class="invalid-feedback">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="mission">Missions</label>
                        <textarea name="mission" id="mission" class="form-control summernote @error('mission') is-invalid  @enderror"> {{ old('mission') }} </textarea>
                        @error('mission')
                            <span class="invalid-feedback">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="goal">Goals</label>
                        <textarea name="goal" id="goal" class="form-control summernote @error('goal') is-invalid  @enderror"> {{ old('goal') }} </textarea>
                        @error('goal')
                            <span class="invalid-feedback">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="target">Targets</label>
                        <textarea name="target" id="target" class="form-control summernote @error('target') is-invalid  @enderror"> {{ old('target') }} </textarea>
                        @error('target')
                            <span class="invalid-feedback">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="image">Image</label>
                        <input type="file" name="image" id="image" class="form-control @error('image') is-invalid  @enderror">
                        @error('image')
                            <span class="invalid-feedback">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>

@stop

@push('style')
    <link rel="stylesheet" href="{{ asset('admin/plugins/summernote/summernote-bs4.min.css') }}">
@endpush

@push('script')
    <script src="{{ asset('admin/plugins/summernote/summernote-bs4.min.js') }}"></script>
    <script>
        $(function(){
            // Summernote
            $('.summernote').summernote()
        })
    </script>
@endpush

resources/views/backend/vision/edit.blade.php
@extends('backend.master')
@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="card card-success">
            <div class="card-header">
                <h3 class="card-title">Edit Vision</h3>
            </div>

            <form action="{{ route('visions.update', $vision) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="card-body">
                    <div class="form-group">
                        <label for="welcome">Welcome Speech Head Of TRPL</label>
                        <textarea name="welcome" id="welcome" class="form-control summernote @error('welcome') is-invalid  @enderror"> {{ old('welcome') ?? $vision->welcome }} </textarea>
                        @error('welcome')
                            <span class="invalid-feedback">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="vision">Our Vision</label>
                        <textarea name="vision" id="vision" class="form-control summernote @error('vision') is-invalid  @enderror"> {{ old('vision') ?? $vision->vision}} </textarea>
                        @error('vision')
                            <span class="invalid-feedback">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="mission">Missions</label>
                        <textarea name="mission" id="mission" class="form-control summernote @error('mission') is-invalid  @enderror"> {{ old('mission') ?? $vision->mission }} </textarea>
                        @error('mission')
                            <span class="invalid-feedback">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="goal">Goals</label>
                        <textarea name="goal" id="goal" class="form-control summernote @error('goal') is-invalid  @enderror"> {{ old('goal') ?? $vision->goal }} </textarea>
                        @error('goal')
                            <span class="invalid-feedback">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="target">Targets</label>
                        <textarea name="target" id="target" class="form-control summernote @error('target') is-invalid  @enderror"> {{ old('target') ?? $vision->target }} </textarea>
                        @error('target')
                            <span class="invalid-feedback">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="image">Image</label>
                        <input type="file" name="image" id="image" class="form-control @error('image') is-invalid  @enderror">
                        @error('image')
                            <span class="invalid-feedback">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>

        </div>
    </div>
</div>

@stop

@push('style')
    <link rel="stylesheet" href="{{ asset('admin/plugins/summernote/summernote-bs4.min.css') }}">
@endpush

@push('script')
    <script src="{{ asset('admin/plugins/summernote/summernote-bs4.min.js') }}"></script>
    <script>
        $(function(){
            // Summernote
            $('.summernote').summernote()
        })
    </script>
@endpush

resources/views/backend/vision/index.blade.php
@extends('backend.master')
@section('content')
<div class="card card-info">
    <div class="card-header">
        <h3 class="card-title">Our Vision</h3>
    </div>
    <div class="card-body">
        
        <a href="{{ route('visions.create') }}" class="btn btn-primary mb-3">Add a new vision</a>
        
        <table id="dataTable" class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Welcome</th>
                    <th>Our Vision</th>
                    <th>Missions</th>
                    <th>Goals</th>
                    <th>Targets</th>
                    <th>Image</th>
                    <th>Action</th>
                </tr>
            </thead>
        </table>
    </div>
</div>
@stop

@push('style')
    <link rel="stylesheet" href="{{ asset('admin/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css') }}">
@endpush

@push('script')
    <script src="{{ asset('admin/plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('admin/plugins/sweetalert2/sweetalert2.js') }}"></script>
    <script src="{{ asset('admin/plugins/sweetalert2/sweetalert2.min.js') }}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#dataTable').DataTable({
                "processing" : true,
                "serverSide" : true,
                "responsive" : true,
                "autoWidth"  : true,
                ajax: '{{ route('data.visions') }}',
                columns: [
                    { data: 'DT_RowIndex', orderable: false, searchable: false },
                    { data: 'welcome' },
                    { data: 'vision' },
                    { data: 'mission' },
                    { data: 'goal' },
                    { data: 'target' },
                    { data: 'image' },
                    { data: 'action' }, 
                ]
            });
        })

        $('#dataTable').on('click', 'button#delete', function(e){
            e.preventDefault();
            var id = $(this).data('id');
            
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'Batal'
                }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        type: "DELETE",
                        url: "/admin/visions/" + id,
                        data: {
                            "id": id,
                            "_token": "{{ csrf_token() }}"
                        },
                        success: function(data){
                            Swal.fire(
                            'Deleted!',
                            'Your file has been deleted.',
                            'success'
                            )
                            location.reload(true)
                        },
                    })
                    
                }
                })
            })
    </script>
@endpush